USE diagcar_ai;

ALTER TABLE users ADD COLUMN IF NOT EXISTS car_brand VARCHAR(120) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS fuel_type VARCHAR(80) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS transmission VARCHAR(80) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mileage INT NULL;
ALTER TABLE diagnostics ADD COLUMN IF NOT EXISTS vehicle_snapshot JSON NULL;
